### ISSUE TITLE
Support named-readtables as a more modern way to enable syntax

### ISSUE THREAD

**Issue by svetlyak40wt** [edicl/cl-interpol#7]
[Named-readtables](http://quickdocs.org/named-readtables/) are more convenient because it's `in-readtable` can be recognized by SLIME and SLY and they will use it information when evaluating regions of the code in the buffer.

I suggest to add something like that into the `cl-interpol` package along with existing `enable-interpol-syntax` macro:

```lisp
(defpackage #:cl-interpol
  (:use #:cl)
  (:import-from #:named-readtables
                #:defreadtable))

(defreadtable :interpol-syntax
   (:merge :standard)
   (:dispatch-macro-char #\# #\? #'cl-interpol:interpol-reader))
```

After that anybody can use it in his code like that:

```lisp
(defpackage #:my-package
  (:use #:cl)
  (:import-from #:named-readtables
                #:in-readtable))

(in-readtable :interpol-syntax)

(format t #?"The package: ${*package*}")
```

I'll make a pull-request if you agreed.

**Comment by svetlyak40wt** [comment]
@vityok @hanshuebner what do you think, guys?

**Comment by svetlyak40wt** [comment]
Guys?

**Comment by hanshuebner** [comment]
I have not used cl-interpol in over a decade and am no longer maintaining any CL software.  That said, I would think that it'd be nice if cl-interpol and named-readtables interoperate.  In the light of quicklisp, adding named-readtables as a dependency to cl-interpol no longer sounds like a terrible idea, however that is just my personal feeling and the current maintainers may feel different.

**Comment by stassats** [comment]
It has to be optional and not break existing code.

**Comment by svetlyak40wt** [comment]
@stassats suggested changes will not break existing code, if don't want to introduce additional dependency to `cl-interpol` system, then another system can be added – `cl-interpol-syntax`. And it will bring all necessary dependency and changes.

@stassats are you mantainer of cl-interpol?

**Comment by svetlyak40wt** [comment]
@stassats Stas?

**Comment by stassats** [comment]
Yes? As I said, I only have one requirement—not breaking existing code.

**Comment by svetlyak40wt** [comment]
@stassats how does `docs/index.html` should be updated? It is a handwritten document or should be generated?

**Comment by svetlyak40wt** [comment]
I've created a pull request: https://github.com/edicl/cl-interpol/pull/8 but probably docs/index.html should be updated as well.

**Comment by hanshuebner** [comment]
docs/index.html is hand-written and needs to be manually updated.

2018-05-08 8:16 GMT+02:00 Alexander Artemenko <notifications@github.com>:

**Comment by svetlyak40wt** [comment]
Ok, I'll update the pull soon.
